# Generated by Django 4.2.25 on 2025-10-26 05:39

import apps.rooms.chat_models
import apps.rooms.recording_models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShareSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('participant_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('stream_id', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration', models.IntegerField(default=0)),
                ('viewer_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('network_in', models.BigIntegerField(default=0)),
                ('network_out', models.BigIntegerField(default=0)),
                ('active_connections', models.PositiveIntegerField(default=0)),
                ('db_connections', models.PositiveIntegerField(default=0)),
                ('db_query_time_avg', models.FloatField(default=0.0)),
                ('redis_connections', models.PositiveIntegerField(default=0)),
                ('redis_memory_used', models.BigIntegerField(default=0)),
                ('redis_keys_count', models.PositiveIntegerField(default=0)),
                ('active_rooms', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('websocket_connections', models.PositiveIntegerField(default=0)),
                ('errors_500', models.PositiveIntegerField(default=0)),
                ('errors_400', models.PositiveIntegerField(default=0)),
                ('timeout_errors', models.PositiveIntegerField(default=0)),
                ('response_time_avg', models.FloatField(default=0.0)),
                ('requests_per_second', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='rooms_syste_timesta_45fb52_idx'), models.Index(fields=['cpu_usage', 'memory_usage'], name='rooms_syste_cpu_usa_9351e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_rooms_created', models.PositiveIntegerField(default=0)),
                ('total_rooms_active', models.PositiveIntegerField(default=0)),
                ('total_rooms_expired', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('unique_participants', models.PositiveIntegerField(default=0)),
                ('avg_participants_per_room', models.FloatField(default=0.0)),
                ('max_participants_in_room', models.PositiveIntegerField(default=0)),
                ('total_session_duration', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.PositiveIntegerField(default=0)),
                ('longest_session', models.PositiveIntegerField(default=0)),
                ('sfu_rooms_created', models.PositiveIntegerField(default=0)),
                ('sfu_rooms_failed', models.PositiveIntegerField(default=0)),
                ('p2p_rooms_used', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(blank=True, default=dict)),
                ('top_cities', models.JSONField(blank=True, default=dict)),
                ('connection_errors', models.PositiveIntegerField(default=0)),
                ('avg_connection_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room Analytics',
                'verbose_name_plural': 'Room Analytics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period', 'period_start'], name='rooms_rooma_period_f8e350_idx'), models.Index(fields=['period_start', 'period_end'], name='rooms_rooma_period__72bef0_idx')],
                'unique_together': {('period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('created_by_id', models.CharField(max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.rooms.recording_models.recording_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['webm', 'mp4', 'mkv'])])),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('include_audio', models.BooleanField(default=True)),
                ('include_video', models.BooleanField(default=True)),
                ('include_screen_share', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['room_id', 'started_at'], name='rooms_recor_room_id_bb3600_idx'), models.Index(fields=['status'], name='rooms_recor_status_c6fb14_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('sender_id', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('system', 'System'), ('notification', 'Notification')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='rooms.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to=apps.rooms.chat_models.chat_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'zip', 'rar', '7z', 'tar', 'gz', 'csv', 'json', 'xml'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('archive', 'Archive'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=255, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rooms.chatmessage')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('room_create', 'Room Created'), ('room_join', 'Room Joined'), ('room_leave', 'Room Left'), ('room_close', 'Room Closed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_suspend', 'User Suspended'), ('system_config', 'System Configuration Changed'), ('analytics_view', 'Analytics Viewed')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='authentication.user')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='rooms_usera_user_id_093f15_idx'), models.Index(fields=['action', 'timestamp'], name='rooms_usera_action_6a941a_idx'), models.Index(fields=['severity', 'timestamp'], name='rooms_usera_severit_3f4df2_idx'), models.Index(fields=['ip_address', 'timestamp'], name='rooms_usera_ip_addr_448ee6_idx'), models.Index(fields=['content_type', 'object_id'], name='rooms_usera_content_57bbbf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room_id', 'created_at'], name='rooms_chatm_room_id_dff582_idx'),
        ),
    ]
