# Generated by Django 4.2.7 on 2025-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('network_in', models.BigIntegerField(default=0)),
                ('network_out', models.BigIntegerField(default=0)),
                ('active_connections', models.PositiveIntegerField(default=0)),
                ('db_connections', models.PositiveIntegerField(default=0)),
                ('db_query_time_avg', models.FloatField(default=0.0)),
                ('redis_connections', models.PositiveIntegerField(default=0)),
                ('redis_memory_used', models.BigIntegerField(default=0)),
                ('redis_keys_count', models.PositiveIntegerField(default=0)),
                ('active_rooms', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('websocket_connections', models.PositiveIntegerField(default=0)),
                ('errors_500', models.PositiveIntegerField(default=0)),
                ('errors_400', models.PositiveIntegerField(default=0)),
                ('timeout_errors', models.PositiveIntegerField(default=0)),
                ('response_time_avg', models.FloatField(default=0.0)),
                ('requests_per_second', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'System Metrics',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='rooms_syste_timesta_45fb52_idx'), models.Index(fields=['cpu_usage', 'memory_usage'], name='rooms_syste_cpu_usa_9351e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField()),
                ('total_rooms_created', models.PositiveIntegerField(default=0)),
                ('total_rooms_active', models.PositiveIntegerField(default=0)),
                ('total_rooms_expired', models.PositiveIntegerField(default=0)),
                ('total_participants', models.PositiveIntegerField(default=0)),
                ('unique_participants', models.PositiveIntegerField(default=0)),
                ('avg_participants_per_room', models.FloatField(default=0.0)),
                ('max_participants_in_room', models.PositiveIntegerField(default=0)),
                ('total_session_duration', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.PositiveIntegerField(default=0)),
                ('longest_session', models.PositiveIntegerField(default=0)),
                ('sfu_rooms_created', models.PositiveIntegerField(default=0)),
                ('sfu_rooms_failed', models.PositiveIntegerField(default=0)),
                ('p2p_rooms_used', models.PositiveIntegerField(default=0)),
                ('top_countries', models.JSONField(blank=True, default=dict)),
                ('top_cities', models.JSONField(blank=True, default=dict)),
                ('connection_errors', models.PositiveIntegerField(default=0)),
                ('avg_connection_time', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room Analytics',
                'verbose_name_plural': 'Room Analytics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period', 'period_start'], name='rooms_rooma_period_f8e350_idx'), models.Index(fields=['period_start', 'period_end'], name='rooms_rooma_period__72bef0_idx')],
                'unique_together': {('period', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('room_create', 'Room Created'), ('room_join', 'Room Joined'), ('room_leave', 'Room Left'), ('room_close', 'Room Closed'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('user_suspend', 'User Suspended'), ('system_config', 'System Configuration Changed'), ('analytics_view', 'Analytics Viewed')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='authentication.user')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='rooms_usera_user_id_093f15_idx'), models.Index(fields=['action', 'timestamp'], name='rooms_usera_action_6a941a_idx'), models.Index(fields=['severity', 'timestamp'], name='rooms_usera_severit_3f4df2_idx'), models.Index(fields=['ip_address', 'timestamp'], name='rooms_usera_ip_addr_448ee6_idx'), models.Index(fields=['content_type', 'object_id'], name='rooms_usera_content_57bbbf_idx')],
            },
        ),
    ]
